### ISSUE TITLE
Positioning issue for the modal in the contact form

### ISSUE THREAD

**Issue by nishi-ai** [nishi-ai/sneakers#8]
![contact_form_modal_issue](https://user-images.githubusercontent.com/60405643/200755769-606ede0c-4796-4a60-bd16-2d8bb5a91605.gif)

# 前提・実現したいこと
モーダルをある特定のセクションに位置設定したい。

# 問題点/エラー内容/エラー文章

- モーダルのスタイル position: absolute, top: 0 初期設定。
- const offset = window.pageYOffset;
または
const contactSection = document.getElementById("contact").offsetTop;

- 取得した値をStringに変えて、setPropertyでプロパティを再設定しようとしているが、位置が上手く設定されない。
- 変更する取得値がwindow.pageYOffsetで、ヘッダーのContactボタンをクリックし自動でスクロールダウンした場合、window.pageYOffsetが０のままなので、モーダルがトップ０へ設定されてしまう。
- 画面のサイズが変わると、Contact Sectionのtopの値も変わり、モーダルの位置が予期せぬ場所へ。

# 該当ソースコード/コマンド
main.js 82行目〜
[js/main.js](https://github.com/nishi-ai/sneakers/pull/7/files#diff-431e5adb210d9982cdf7bacdacad1bab1cd70c57028cb41316d8bb79d2d8b046)

# 想定している処理の流れ

1. モーダルの初期位置の見直し
2. Section#contact の正しい位置の取得
3. その値にモーダルのtopの値を変更
4. もしくは、CSSだけでModalの位置を変えられるか。

# うまくいっている部分
モダールのオープン、クローズ自体は機能している。

# エラー原因となり得る部分
モーダルの初期位置を relative か absolute？

# 試したことや調べたこと
- CSSの値をJSで変更する方法

# 補足情報
参考サイト：https://dotinstall.com/lessons/modal_js_v3/54108
https://stackdiary.com/snippet/change-css-variable-value-javascript/
https://stackoverflow.com/questions/28597241/how-to-position-a-relative-element-in-the-same-coordinates-as-his-parent-in-the

# コードURL(Github、Fiddle、Codepenなど該当コードファイル)
https://github.com/nishi-ai/sneakers/pull/7/files#diff-431e5adb210d9982cdf7bacdacad1bab1cd70c57028cb41316d8bb79d2d8b046

**Comment by kasuyaofcb** [comment]
お疲れ様です。
確認いたしました。
他の方のリポジトリにpushした事が無いので、メッセージで返事いたしますね。
やった事は大した事ないですで。

単純にCSSでposition:fixedを使用してモーダルを画面に対しての絶対位置で固定してしまえば良いのではと思いました。

変更点は下記のみです。
```

#modal {
  background: #fff;
  max-width: 400px;
  padding: 20px;
  border-radius: 4px;
  // position: absolute;
  // top: var(--top-change);
  // left: 0;
  // right: 0;

  // kasuya追記
  position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  margin: 0 auto;
}

```

**Comment by nishi-ai** [comment]
@kasuyaofcb
ありがとうございます！！解決しました！🥳
